# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-14 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('jop', models.CharField(max_length=250)),
                ('pic', models.FileField(upload_to='')),
            ],
        ),
    ]
