# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-14 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_members'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='members',
            new_name='memberss',
        ),
    ]
