# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-14 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20170214_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250)),
                ('jop', models.CharField(max_length=250)),
                ('pic', models.FileField(upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='speaker',
            old_name='event',
            new_name='speaker',
        ),
        migrations.RemoveField(
            model_name='memberss',
            name='email',
        ),
        migrations.RemoveField(
            model_name='memberss',
            name='jop',
        ),
        migrations.RemoveField(
            model_name='memberss',
            name='pic',
        ),
        migrations.AddField(
            model_name='information',
            name='information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.memberss'),
        ),
    ]
