# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-14 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20170214_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='information',
            new_name='memberss',
        ),
        migrations.RenameField(
            model_name='speaker',
            old_name='speaker',
            new_name='event',
        ),
    ]
