# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-14 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20170214_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='memberss',
            new_name='spp_member',
        ),
    ]
