# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-14 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20170214_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='spp_member',
        ),
        migrations.AddField(
            model_name='memberss',
            name='email',
            field=models.CharField(default='email', max_length=250),
        ),
        migrations.AddField(
            model_name='memberss',
            name='jop',
            field=models.CharField(default='   ', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberss',
            name='pic',
            field=models.FileField(default='  ', upload_to=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='information',
        ),
    ]
