# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-17 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='prjimages/%Y/%m/%d/%H/%M/%S/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Project')),
            ],
        ),
        migrations.DeleteModel(
            name='gallery',
        ),
    ]
