# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-12 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20170217_0428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='eventt',
        ),
    ]
