# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-19 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gallery',
        ),
    ]
