# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-20 02:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_imagess'),
    ]

    operations = [
        migrations.DeleteModel(
            name='imagess',
        ),
        migrations.RemoveField(
            model_name='images',
            name='row',
        ),
        migrations.DeleteModel(
            name='row',
        ),
    ]
